### ISSUE TITLE
Firefox on Nexus 4: id tags

### ISSUE THREAD

**Issue by kayleemenard** [marisabivi/portfolio#7]
First, when tapping on a portfolio item (in portfolio and landscape view), the newly loaded page displays the description for item a above item b, which is a little confusing visually.
![2015-10-08 13 20 12](https://cloud.githubusercontent.com/assets/6373202/10367486/cacb14c6-6d9e-11e5-8669-32d2ee3cda06.png)

![2015-10-08 13 20 42](https://cloud.githubusercontent.com/assets/6373202/10367485/caca9032-6d9e-11e5-98bb-ec0de281c74c.png)

Additionally, your footers on your index page and your index with description are different. When tapping on the contact button from your "index with description" page, it sends you to what seems to be a random place on your index page, rather than directing you to information/full footer.
![2015-10-08 13 21 09](https://cloud.githubusercontent.com/assets/6373202/10367484/cac94718-6d9e-11e5-9859-b4a90867038b.png)
![2015-10-08 13 21 14](https://cloud.githubusercontent.com/assets/6373202/10367487/cacb5c2e-6d9e-11e5-9222-33a2c33e080c.png)

**Comment by marisabivi** [comment]
Thanks!
